### PR TITLE
form alert for dashboard and proposals

### LINKED ISSUE #628: form validation error messages not very visible
The error messages when you post incorrect info for a new proposal don’t stand out enough and the bullet points don’t make sense if there is just one error.

bildschirmfoto 2017-01-24 um 14 27 30

### PR DESCRIPTION
**Pull request by damusp**
fixes #628 and makes form validation error messages stand out.

### CODE REVIEW

**Comment by slomo** [comment]
Looks good. But maybe there are some issues on smaller screens here.

**Comment by slomo** [comment]
Also our use of `$brand-danger' for error messages is not consistent. But maybe it should be?

**Comment by damusp** [comment]
Thanks Yves. I agree fully with 1) and 2) 

1) I guess I'll try to use another margin to stop the text from overlapping the icon
2) Right, one red is quite enough. I'll take a look if I can set this right

**Comment by slomo** [comment]
Could you give a status update here? Should this be continued by someone else?

**Pull request merged**
