### PR TITLE
improve paragraph edit form

### PR DESCRIPTION
**Pull request by slomo**
- add animation
- prevent creation of new paragraphs from moving
- prevent creating multiple document on first create
- lower up and down flickering by resizing textareas

solves #381 ???

### CODE REVIEW

**Comment by MagdaN** [comment]
initial creation of document fails with: {"paragraphs":[{"weight":["Dieses Feld muss ausgefüllt werden."]}]}

**Comment by MagdaN** [comment]
I think the buttons should be disabled and not invisible when moving up or down does not make sense

**Comment by MagdaN** [comment]
When I changed the order of two paragrpahs and press save the order is changed back to what it was before

**Comment by slomo** [comment]
@MagdaN all issues addressed, could you test again

**Comment by MagdaN** [comment]
@slomo when I add a new paragraph in between two paragraphs it gets posted immediately an I get error messages saying that the headline and the text of the new paragraph should not be empty.

**Pull request merged**
