### PR TITLE
add doc for css guidelines

### PR DESCRIPTION
**Pull request by vellip**

### CODE REVIEW

**Comment by slomo** [comment]
Very nice. Reading about it, it seems that we might consider to somehow differentiate between modifier and children. Do you think this can be useful, or rather to complicated?

**Comment by vellip** [comment]
I think it would be useful! I am however not sure, if we find a good way
that everyone is happy with. Bootstrap does make no difference and if we
deviate from Bootstrap we could also just use BEM again.

A simpler/more bootstrap-close solution might be to add an "is" in front of
the modifier, like `.tweet-title-islarge` I'd rather not add a dash after
the "is" though, because it feels somewhat inconsistent that way.

Otherwise we might just look at BEM for this one and use
`.tweet-title--large`.

I don't mind either, just wanting to say, this is not what Bootstrap does,
so the argument to use Bootstrap as reference gets somewhat invalid then.
Though it would still be closer to Bootstrap than BEM.

Let's talk about it tomorrow.

**Comment by vellip** [comment]
After discussing it: We won't make a difference between modifier and child element.

**Comment by MagdaN** [comment]
I think this very good. Thanks, for creating it. Should I merge?

**Comment by vellip** [comment]
I am fine with it!

**Pull request merged**
