### PR TITLE
Add generic relations to documents

### LINKED ISSUE #396: Use Generic Relation everywhere where generic fks are used

### PR DESCRIPTION
**Pull request by slomo**
~~fixes #396~~

### CODE REVIEW

**Comment by MagdaN** [comment]
Should we not use a generic relation in comment to get the child comments?

**Comment by vellip** [comment]
I can't add a paragraph filling out the (actually optional) headlines.

**Comment by vellip** [comment]
When the create phase is over and the paragraphs should be shown, there is an error: "'RelatedManager' object is not iterable" at "{% for paragraph in object.paragraphs %}"

**Comment by vellip** [comment]
Being a normal user, I don't get the comment box on the whole document_detail, only for the detail paragraph view. (There's probably some component returning nothing/undefined in jsx)

**Comment by vellip** [comment]
Also, the comment count is not shown (renders 0), needs an `.all` in document_detail:17

**Comment by slomo** [comment]
@vellip you can also leave line comments ;)

**Comment by slomo** [comment]
@vellip @MagdaN addressed your issues

**Comment by slomo** [comment]
@MagdaN generic relations for comments will be on a different pull request

**Comment by MagdaN** [comment]
@slomo are you going to add an new issue?

**Pull request merged**
