### PR TITLE
Pv 2016 11 update profile form

### LINKED ISSUE #503: Dashboard: Edit profile form changes
Thanks for releasing the new user profile on the dev server. Here are some changes for the dashboard form I’d like to see implemented.

unknown-33

### PR DESCRIPTION
**Pull request by vellip**
fixes #503

### CODE REVIEW

**Comment by slomo** [comment]
You probably have to create new migrations in order to get this working.

**Comment by vellip** [comment]
@slomo works now!

**Comment by slomo** [comment]
Not strictly related, but could we open the social profiles in a new tab.

**Comment by vellip** [comment]
@slomo, done!

**Pull request merged**
