### PR TITLE
add file upload widget

### PR DESCRIPTION
**Pull request by MagdaN**
this is pretty similar to the image upload widget in core, we should check, if this is needed in core also.

### CODE REVIEW

**Comment by slomo** [comment]
This behaves a bit differently than the image upload in regards to deleting files.

**Comment by slomo** [comment]
I just saw you discussion with @damusp in zepplin. So I guess we'll merge this first? Will there be an additional story to fix the remaining issues in the upload form?

**Comment by MagdaN** [comment]
What remaining issues do you mean?

**Comment by slomo** [comment]
As far as I understand there should be a delete button similar to the one for the images.

**Pull request merged**
