### PR TITLE
2016 06 cc projects carousel

### PR DESCRIPTION
**Pull request by localgrr**
Added carousel to projects page + a plugin. The example in project_detail.html is just an example though, this should be overwritten by real data.

### CODE REVIEW

**Comment by MagdaN** [comment]
@localgrr did you forget to commit _carousel.scsss

**Comment by MagdaN** [comment]
@localgrr can you change the js?

**Comment by MagdaN** [comment]
Is this supposed to look like that? Or should the tiles on the right- and the lefthand side of the arrows disappear? 
bildschirmfoto 2016-07-19 um 10 42 17

**Comment by NadineKarbach** [comment]
@MagdaN The titles, actually the whole box, left and right the arrow should disappear in the sense of being blurred white/shadow white

**Comment by localgrr** [comment]
@NadineKarbach that blurring function is a bit cryptic, I'd prefer to keep it simple for now

**Comment by localgrr** [comment]
OK I made that blur out thing, i still think there should be a forward and back navigation though ? @nicoladimarco ?

**Comment by nicoladimarco** [comment]
@localgrr @MagdaN  the best would be if the arrows would appear on top of the semi transparent card (both left and right )

**Comment by localgrr** [comment]
I took away the faded opacity option on mobile, tbh I think we should remove it in general it makes the interface a bit clunky imho

**Pull request merged**
