### PR TITLE
Improve image upload widget

### PR DESCRIPTION
**Pull request by localgrr**
Better file uploading

### CODE REVIEW

**Comment by MagdaN** [comment]
Looks good on create form but I am using the same form also for updating, and here it looks not so good:
bildschirmfoto 2016-08-04 um 10 09 09

**Comment by MagdaN** [comment]
Errors used to look like that, can you fix this please: 
bildschirmfoto 2016-08-04 um 10 14 34

**Comment by localgrr** [comment]
Hi @MagdaN  can you expand out the upload field template tag so I can have more control over the HTML please ? thanks

**Comment by slomo** [comment]
Okay, what is going on here? This pull-request is open since quite some time. Can we get it flying again?

**Comment by MagdaN** [comment]
@slomo we need to figure out how to style the 'change image field'

**Comment by slomo** [comment]
I have added a custom widget for the form, by overriding some values of the original widget. We could now continue to override even more (changing the html structure completely), but that would be not that trivial. Maybe either @localgrr  or @vellip can give me hint, what we would actually require here in terms of html.

**Comment by slomo** [comment]
This looks very odd. I would say we should try to rebase this, rather than merging because now it contains  over 2000 lines of code ;)

**Comment by slomo** [comment]
Fixed by rebase and force push

**Pull request merged**
