### PR TITLE
Add basic platform users

### PR DESCRIPTION
**Pull request by slomo**
Add basic functionality for platform users:

 - login + logout ui
 - register flow
 - user indicator in basetemplate

Open issues:

- [x] migration should currently not work
- [ ] styling is required

### CODE REVIEW

**Comment by MagdaN** [comment]
Looks good

**Comment by MagdaN** [comment]
@slomo I added the indicator to the top menu. If the changes are fine with you, maybe @localgrr could finalize the styling?

**Comment by localgrr** [comment]
Sure

**Comment by localgrr** [comment]
@slomo added styling

**Pull request merged**
